version: '3.8'
services:
  reddit-mcp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MCP_SERVER_NAME=reddit-mcp
      - MCP_SERVER_VERSION=1.0.0
      - REDDIT_USER_AGENT=reddit-mcp-server/1.0.0
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3